### ISSUE TITLE
Clickable examples in the README?

### ISSUE THREAD

**Issue by EmilStenstrom** [LeaVerou/nudeui#7]
Hi! The readme is great, I was just wondering if it would be possible to see the result of each code snippets right below it? Makes it much easier to understand (to me at least), when I can see both the code and the result side by side.

**Comment by LeaVerou** [comment]
If you view them on the website, they should show the result right above. If they don't, that's a bug. Which browser/OS?

**Comment by EmilStenstrom** [comment]
Using latest Firefox (104.0b9) on Windows 10. Ublock Origin is on, but didn't block anything. 

![image](https://user-images.githubusercontent.com/224130/184540437-291eeed9-a612-4f58-8b22-a1f7b36fe189.png)

I just now looked in the console, and saw this error:
![image](https://user-images.githubusercontent.com/224130/184540529-5041d817-7fc8-4d95-9434-dc18d949c5ec.png)

Could that be it?

**Comment by LeaVerou** [comment]
Thanks, should be fixed now!

**Comment by EmilStenstrom** [comment]
Looks great, thanks for sharing these with everyone! :)
