### ISSUE TITLE
nd-rating key events don't work if you tab to the component

### ISSUE THREAD

**Issue by derikb** [LeaVerou/nudeui#9]
Was checking out the nd-rating component with some colleagues and we noticed that the left/right arrow key events only seem to work if you are mousing over the component. If you tab to the component it takes focus, but the arrow keys don't let you edit it.

**Comment by LeaVerou** [comment]
Huh, that's very strange, I'd swear this worked before. Thanks, will look into it!

**Comment by LeaVerou** [comment]
That's so bizarre. They work when the component is focused via clicking, but not when tabbing to it. The `keydown` event doesn't even fire at all! 😕

**Comment by derikb** [comment]
I think you probably need to enable/disable `this.edit` on focus/blur.

**Comment by derikb** [comment]
It's not really the focus by clicking, it's the mouse being over the component. If you click and then move the mouse away it doesn't work either.

**Comment by LeaVerou** [comment]
Thanks, I think it's fixed now!
